-- Habilitar la extensión PostGIS para geolocalización
create extension if not exists postgis;

-- Tabla de Motos
create table motorcycles (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  model text,
  vin text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Telemetría (Datos en tiempo real del ESP32)
create table telemetry (
  id bigint generated by default as identity primary key,
  motorcycle_id uuid references motorcycles(id) on delete cascade not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  latitude double precision,
  longitude double precision,
  speed double precision, -- en km/h
  battery_level integer, -- porcentaje 0-100
  battery_voltage double precision,
  is_charging boolean default false,
  signal_strength integer, -- RSSI de la SIM
  location geography(point) -- Para búsquedas espaciales
);

-- Tabla de Recorridos (Procesados o guardados)
create table trips (
  id uuid default gen_random_uuid() primary key,
  motorcycle_id uuid references motorcycles(id) on delete cascade not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  distance double precision, -- en km
  avg_speed double precision,
  max_speed double precision,
  path jsonb -- Array de coordenadas para dibujar el trayecto
);

-- Índices para mejorar el rendimiento
create index telemetry_motorcycle_id_idx on telemetry(motorcycle_id);
create index telemetry_timestamp_idx on telemetry(timestamp desc);
create index telemetry_location_idx on telemetry using gist(location);

-- Función para actualizar el punto geográfico automáticamente
create or replace function update_location_point()
returns trigger as $$
begin
  if new.latitude is not null and new.longitude is not null then
    new.location = st_setseid(st_point(new.longitude, new.latitude), 4326)::geography;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger tr_update_telemetry_location
before insert on telemetry
for each row execute function update_location_point();
