-- Habilitar la extensión PostGIS para geolocalización
create extension if not exists postgis;

-- Tabla de Motos
create table if not exists motorcycles (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  model text,
  vin text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Telemetría (Datos en tiempo real del ESP32)
create table if not exists telemetry (
  id bigint generated by default as identity primary key,
  motorcycle_id text not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null,
  latitude double precision,
  longitude double precision,
  speed double precision, -- en km/h
  battery_level integer, -- porcentaje 0-100
  battery_voltage double precision,
  is_charging boolean default false,
  signal_strength integer, -- RSSI de la SIM
  location geography(point), -- Para búsquedas espaciales
  
  -- Nuevos campos para Baterías Duales
  moto_battery integer,
  moto_battery_b integer,
  bat_a_volts double precision,
  bat_a_amps double precision,
  bat_a_temp double precision,
  bat_b_volts double precision,
  bat_b_amps double precision,
  bat_b_temp double precision,
  is_charging_b boolean default false,
  location_type text,
  date text,
  is_trip_active boolean default false
);

-- Tabla para configuración manual de CAN (agnóstica a la marca)
create table if not exists can_configurations (
  id uuid default gen_random_uuid() primary key,
  motorcycle_id text not null unique,
  
  -- Batería A: Voltaje
  v_id integer default 1284,
  v_start integer default 2,
  v_len integer default 2,
  v_factor float default 0.01,
  v_be boolean default true,
  
  -- Batería A: Corriente
  c_id integer default 1284,
  c_start integer default 4,
  c_len integer default 2,
  c_factor float default 0.1,
  c_signed boolean default true,
  c_be boolean default true,
  
  -- Batería A: SOC
  s_id integer default 1344,
  s_start integer default 0,
  s_len integer default 1,
  s_factor float default 1.0,
  s_be boolean default true,
  
  -- Batería A: Temperatura
  t_id integer default 1344,
  t_start integer default 3,
  t_len integer default 1,
  t_factor float default 1.0,
  t_be boolean default true,
  
  -- Batería B: Voltaje
  vb_id integer default 1285,
  vb_start integer default 2,
  vb_len integer default 2,
  vb_factor float default 0.01,
  vb_be boolean default true,
  
  -- Batería B: Corriente
  cb_id integer default 1285,
  cb_start integer default 4,
  cb_len integer default 2,
  cb_factor float default 0.1,
  cb_signed boolean default true,
  cb_be boolean default true,
  
  -- Batería B: SOC
  sb_id integer default 1345,
  sb_start integer default 0,
  sb_len integer default 1,
  sb_factor float default 1.0,
  sb_be boolean default true,
  
  -- Batería B: Temperatura
  tb_id integer default 1345,
  tb_start integer default 3,
  tb_len integer default 1,
  tb_factor float default 1.0,
  tb_be boolean default true,
  
  -- Sistema: Inyección de hora en CAN
  time_tx_id integer default 1296,
  time_hour_byte integer default 5,
  time_min_byte integer default 6,
  
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabla de Recorridos (Procesados o guardados)
create table if not exists trips (
  id uuid default gen_random_uuid() primary key,
  motorcycle_id text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone,
  distance double precision, -- en km
  avg_speed double precision,
  max_speed double precision,
  consumption integer, -- porcentaje consumido
  start_battery_level integer,
  end_battery_level integer,
  path jsonb -- Array de coordenadas [[lat, lng], ...]
);

-- Índices para mejorar el rendimiento
create index telemetry_motorcycle_id_idx on telemetry(motorcycle_id);
create index telemetry_timestamp_idx on telemetry(timestamp desc);
create index telemetry_location_idx on telemetry using gist(location);

-- Función para actualizar el punto geográfico automáticamente
create or replace function update_location_point()
returns trigger as $$
begin
  if new.latitude is not null and new.longitude is not null then
    new.location = st_setsrid(st_point(new.longitude, new.latitude), 4326)::geography;
  end if;
  return new;
end;
$$ language plpgsql;

create trigger tr_update_telemetry_location
before insert on telemetry
for each row execute function update_location_point();

-- Función para gestionar trayectos automáticamente
create or replace function process_telemetry_trip()
returns trigger as $$
declare
  active_trip_id uuid;
begin
  -- Solo procesar si el trayecto está activo
  if new.is_trip_active then
    -- Buscar si ya existe un trayecto abierto (sin end_time) para esta moto
    select id into active_trip_id 
    from trips 
    where motorcycle_id = new.motorcycle_id 
    and end_time is null
    limit 1;

    if active_trip_id is null then
      -- Crear nuevo trayecto
      insert into trips (motorcycle_id, start_time, path, max_speed, start_battery_level, consumption)
      values (
        new.motorcycle_id, 
        new.timestamp, 
        jsonb_build_array(jsonb_build_array(new.latitude, new.longitude)),
        new.speed,
        new.moto_battery,
        0
      );
    else
      -- Actualizar trayecto existente
      update trips 
      set 
        path = path || jsonb_build_array(jsonb_build_array(new.latitude, new.longitude)),
        max_speed = greatest(max_speed, new.speed),
        consumption = start_battery_level - new.moto_battery
      where id = active_trip_id;
    end if;
  else
    -- Si el trayecto NO está activo, cerrar cualquier trayecto abierto
    update trips 
    set 
      end_time = new.timestamp,
      end_battery_level = new.moto_battery,
      consumption = start_battery_level - new.moto_battery
    where motorcycle_id = new.motorcycle_id 
    and end_time is null;
  end if;
  
  return new;
end;
$$ language plpgsql;

-- Trigger para procesar trayectos
create trigger tr_process_telemetry_trip
after insert on telemetry
for each row execute function process_telemetry_trip();
